config:
  BinderHub:
    use_registry: true
    image_prefix: prasanthkothuri/swan-binder-
    hub_url: https://swan-dev.cern.ch
    auth_enabled: true
    build_image: jupyter/repo2docker:0.11.0-54.gbbc3ee0
    image_prefix: prasanthkothuri/swan-binder-

service:
  annotations:
    prometheus.io/scrape: 'false'
  type: NodePort
  nodePort: 30193

image:
  name: prasanthkothuri/binderhub
  tag: 'latest'

retries:
  count: 1
  delay: 4

baseUrl: /

cors: &cors
  allowOrigin: "*"

ingress:
  enabled: true
  https:
    enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http, https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/custom-request-headers: X-Scheme:https
  tls:
    - secretName: swan-binder-cern-ch
      hosts:
        - swan-binder.cern.ch
  hosts:
    - swan-binder.cern.ch

extraEnv:
  - name: REQUESTS_CA_BUNDLE
    value: "/etc/ssl/certs/ca-certificates.crt"

jupyterhub:
  custom:
    binderauth_enabled: true
  hub:
    allowNamedServers: true
    namedServerLimitPerUser: 10
    services:
      binder:
        oauth_no_confirm: true
        oauth_redirect_uri: "https://swan-binder.cern.ch/oauth_callback"
        oauth_client_id: "binder-service"

  singleuser:
    cmd: jupyterhub-singleuser

  auth: {}

