apiVersion: v2
#
name: swan
type: application

# version set by bump2version search/replace
version: 1.2.1 # __swan_version__

appVersion: 0.1.2 # Using swanhub version
#
description: A fully-fledged SWAN instance with jupyterhub, EOS, and CVMFS
icon: https://swan.docs.cern.ch/images/logos/logo_swan_letters.png
#
dependencies:
  - name: jupyterhub
    version: 3.1.0
    repository: https://jupyterhub.github.io/helm-chart/

  - name: fusex
    version: 0.1.3
    repository: https://registry.cern.ch/chartrepo/eos
    condition: eos.deployDaemonSet
  - name: eosxd
    version: 5.1.27-1
    repository: http://registry.cern.ch/chartrepo/cern
    condition: eos.deployCsiDriver

  - name: cvmfs
    version: 0.0.8
    repository: oci://registry.cern.ch/sciencebox/charts
    condition: cvmfs.deployDaemonSet
  - name: cvmfs-csi
    version: 0.1.0
    repository: http://registry.cern.ch/chartrepo/cern
    condition: cvmfs.deployCsiDriver
