apiVersion: v2
#
name: swan
type: application
version: 0.1.0
appVersion: 0.1.1 # Using swanhub version
#
description: A fully-fledge SWAN instance with jupyterhub, EOS, and CVMFS
icon: https://swan.docs.cern.ch/images/logos/logo_swan_letters.png
#
dependencies:
  - name: jupyterhub
    version: 1.1.3
    repository: https://jupyterhub.github.io/helm-chart/

  - name: fusex
    version: 0.1.0
    repository: https://registry.cern.ch/chartrepo/eos
    condition: eos.deployDaemonSet
  - name: eosxd
    version: 0.2.8
    repository: http://registry.cern.ch/chartrepo/cern
    condition: eos.deployCsiDriver

  - name: cvmfs
    version: 0.0.4
    repository: https://registry.cern.ch/chartrepo/sciencebox
    condition: cvmfs.deployDaemonSet
  - name: cvmfs-csi
    version: 0.1.0
    repository: http://registry.cern.ch/chartrepo/cern
    condition: cvmfs.deployCsiDriver
