apiVersion: v2
#
name: swan
type: application

# version set by bump2version search/replace
version: 2.3.44 # __swan_version__

appVersion: 0.1.2 # Using swanhub version
#
description: A fully-fledged SWAN instance with jupyterhub, EOS, and CVMFS
icon: https://swan.docs.cern.ch/images/logos/logo_swan_letters.png
#
dependencies:
  - name: jupyterhub
    version: 3.1.0
    repository: https://jupyterhub.github.io/helm-chart/
  - name: eosxd-csi
    version: 1.4.2
    repository: oci://registry.cern.ch/kubernetes/charts
    condition: eosxd-csi.enabled
  - name: cvmfs-csi
    version: 2.5.2
    repository: oci://registry.cern.ch/kubernetes/charts
    condition: cvmfs-csi.enabled
