{{- range $name, $values := .Values.managedAddons }}
---
apiVersion: v1
kind: Secret
metadata:
  name: managed-addons-{{ $name }}
  namespace: kube-system
stringData:
  values.yaml: |-
{{ toYaml (dict $name $values) | indent 4 }}
{{- end }}
