apiVersion: v2
#
name: swan-cern-system
type: application
# version set by bump2version search/replace
version: 0.0.11 # __swan-cern-system_version__
appVersion: 0.0.1
#
description: The chart to deploy SWAN system components at CERN
#
dependencies:
  - name: fluentd
    version: 0.5.3
    repository: https://fluent.github.io/helm-charts
  - name: gpu-operator
    version: v25.3.0
    repository: oci://registry.cern.ch/kubernetes/charts
    condition: gpu-operator.enabled
  - name: cern-it-monitoring-kubernetes
    version: 3.0.0
    repository: oci://registry.cern.ch/monit
    condition: cern-it-monitoring-kubernetes.enabled
