apiVersion: v2
#
name: swan-cern-system
type: application
# version set by bump2version search/replace
version: 0.0.25 # __swan-cern-system_version__
appVersion: 0.0.1
#
description: The chart to deploy SWAN system components at CERN
#
dependencies:
  - name: gpu-operator-cern
    version: 0.0.3
    repository: oci://registry.cern.ch/kubernetes/charts
    condition: gpu-operator-cern.enabled
  - name: cern-it-monitoring-kubernetes
    version: 3.5.0
    repository: oci://registry.cern.ch/monit
    condition: cern-it-monitoring-kubernetes.enabled
  - name: kafka-streams-apps
    version: 0.0.5
    repository: oci://registry.cern.ch/swan/charts
    condition: kafka-streams-apps.affiliation.enabled