apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd
  namespace: {{ $.Release.Namespace }}
data:
  fluentdDeamon.conf: |-
    # do not collect fluentd logs to avoid infinite loops.
    <match kubernetes.var.log.containers.fluentd**>
      @type null
    </match>

{{ if not .Values.output.includeInternal }}
    <match kubernetes.var.log.containers.**_kube-system_**>
        @type null
    </match>
{{ end }}

    # read from container logs
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    # add some basic metadata to the records
    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>

{{ .Values.parsingConfig | indent 4 }}
  install-plugins.sh: |-
    #!/bin/sh
  {{- range $plugin := .Values.plugins }}
    fluent-gem install {{ $plugin }}
  {{- end }}
    exec /run.sh