{{- if eq .Values.role "consumer" }}
apiVersion: v1
data:
  kubeconfig: {{ .Values.remoteCluster.kubeconfig }}
kind: Secret
metadata:
  name: cplane-secret
  namespace: {{ include "liqo.tenantNamespace" . }}
  labels:
    liqo.io/identity-type: ControlPlane
    liqo.io/remote-cluster-id: {{ .Values.remoteCluster.clusterId }}
  annotations:
    liqo.io/remote-tenant-namespace: liqo-tenant-{{ .Values.clusterId }}
{{- end }}
