# Secret containing the kubeconfig of the remote cluster control plane,
# used for establishing consumer-side peering.
{{- if eq .Values.role "consumer" }}
apiVersion: v1
data:
  kubeconfig: {{ .Values.remoteCluster.kubeconfig }}
kind: Secret
metadata:
  name: kubeconfig-controlplane-{{ .Values.remoteCluster.clusterId }}
  namespace: {{ include "liqo.tenantNamespace" . }}
  labels:
    liqo.io/identity-type: ControlPlane
    liqo.io/remote-cluster-id: {{ .Values.remoteCluster.clusterId }}
  annotations:
    liqo.io/remote-tenant-namespace: liqo-tenant-{{ .Values.clusterId }}
{{- end }}
