# Secret containing the WireGuard public and private keys used for secure network peering.
apiVersion: v1
kind: Secret
metadata:
  name: gw-{{ .Values.remoteCluster.clusterId }}
  namespace: {{ include "liqo.tenantNamespace" . }}  
  labels:
    liqo.io/remote-cluster-id: {{ .Values.remoteCluster.clusterId }}
    networking.liqo.io/gateway-resource: "true"
type: Opaque
data:
  privateKey: {{ .Values.privateWireguardKey }}
  publicKey: {{ .Values.publicWireguardKey }}