# PublicKey resource that stores the WireGuard public key of the remote cluster,
# used to authenticate and establish secure communication with its gateway.
apiVersion: networking.liqo.io/v1beta1
kind: PublicKey
metadata:
  name: gw-publickey
  namespace: {{ include "liqo.tenantNamespace" . }}
  labels:
    liqo.io/remote-cluster-id: {{ .Values.remoteCluster.clusterId }}
    networking.liqo.io/gateway-resource: "true"
spec:
  publicKey: {{ .Values.remoteCluster.publicWireguardKey }}