# RoleBinding to grant the remote cluster's control plane the necessary permissions 
# to interact with resources in the provider cluster.
{{- if eq .Values.role "provider" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.remoteCluster.clusterId }}
  namespace: {{ include "liqo.tenantNamespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: liqo-binding-liqo-remote-controlplane
  namespace: {{ include "liqo.tenantNamespace" . }}
  labels:
    liqo.io/remote-cluster-id: {{ .Values.remoteCluster.clusterId }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: liqo-remote-controlplane
subjects:
- kind: ServiceAccount
  name: {{ .Values.remoteCluster.clusterId }}
  namespace: {{ include "liqo.tenantNamespace" . }}
{{- end }}
