{{- if index .Values "gpu-operator" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kernel-module-params
  namespace: {{ .Release.Namespace }}
data:
  nvidia.conf: |
    NVreg_RestrictProfilingToAdminUsers=0
{{- end }}
