{{- if index .Values "gpu-operator" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-grid-license
  namespace: {{ .Release.Namespace }}
data:
  gridd.conf: |
    ServerAddress=dlsnvidia01.cern.ch
    ServerPort=7070
    BackupServerAddress=dlsnvidia02.cern.ch
    BackupServerPort=7070
    FeatureType=1
{{- end }}
