{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) (index .Values "gpu-operator" "enabled") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-gpu-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: nvidia-gpu-device-plugin
    chart: nvidia-gpu
    release: cern-magnum
spec:
  endpoints:
    - port: gpu-metrics
      honorLabels: true
      relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        regex: ^(.*)$
        targetLabel: instance
        replacement: $1
        action: replace
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
{{- end }}
