apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubspark
  namespace: {{ .Release.Namespace }}
  labels:
    app: hubspark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubspark
  template:
    metadata:
      labels:
        app: hubspark
        hub.jupyter.org/network-access-proxy-api: "true"
        hub.jupyter.org/network-access-proxy-http: "true"
        hub.jupyter.org/network-access-singleuser: "true"
    spec:
      containers:
      - name: hubspark
        env:
        - name: JUPYTERHUB_API_URL
          value: http://hub:8081/hub/api
        - name: JUPYTERHUB_SERVICE_PREFIX
          value: /services/hubspark
        - name: JUPYTERHUB_SERVICE_URL
          value: http://hubspark:1111
        - name: JUPYTERHUB_API_TOKEN
          value: super-secret
          #      valueFrom:
          #        secretKeyRef:
          #          key: jupyterhub_api_token
          #          name: hubspark
        image: gitlab-registry.cern.ch/krraghav/test-container-registry:hubspark
        imagePullPolicy: Always
        ports:
        - containerPort: 1111
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 0
          runAsUser: 0
        volumeMounts:
        - mountPath: /cvmfs
          name: cvmfs
        - name: swan-secrets
          mountPath: /hubspark/hadoop.cred
          subPath: hadoop.cred
        - name: swan-tokens-scripts
          mountPath: /hubspark/hadoop_token.sh
          subPath: hadoop_token.sh

      dnsPolicy: ClusterFirst
      volumes:
      - name: hubspark
        secret:
          defaultMode: 420
          secretName: hubspark
      - name: cvmfs
        hostPath:
          path: /var/cvmfs
          type: Directory
      - name: swan-secrets
        secret:
          defaultMode: 0777
          secretName: swan-cern
          items:
            - key: hadoop.cred
              path: hadoop.cred
      {{- with .Values.hubspark.extraVolumes }}
        {{- . | toYaml | nindent 6 }}
      {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: jupyterhub
    component: hub
  name: hubspark
  namespace: {{ .Release.Namespace }}
data:
  jupyterhub_api_token: c3VwZXItc2VjcmV0Cg==
---
apiVersion: v1
kind: Service
metadata:
  name: hubspark
spec:
  selector:
    app: hubspark
  ports:
    - protocol: TCP
      port: 1111
      targetPort: 1111
