{{- if index .Values "enabled" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hub-metrics-servicemonitor
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: jupyterhub
      component: hub
      release: {{ .Release.Name }}
  endpoints:
  - port: hub
    interval: 30s
    path: /hub/metrics
    bearerTokenSecret:
      name: hub
      key: hub.services.prometheus-service-monitor.apiToken
{{- end }}