{{ if .Values.hpc.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hpc-volume
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: hpc-volume
    nodeStageSecretRef:
      name: hpc-volume-secret
      namespace: {{ $.Release.Namespace }}
    nodePublishSecretRef:
      name: hpc-volume-secret
      namespace: {{ $.Release.Namespace }}
    volumeAttributes:
      monitors: {{ $.Values.hpc.monitors }}
      rootPath: {{ $.Values.hpc.rootPath }}
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hpc-volume-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: hpc-volume
{{- end }}
