kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: swan
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["secrets", "services"]
    verbs: ["get", "watch", "list", "create", "delete", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: swan
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: hub
roleRef:
  kind: Role
  name: swan
  apiGroup: rbac.authorization.k8s.io