apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: swan
  namespace: {{ .Release.Namespace }}
data:
{{ if eq .Values.jupyterhub.hub.db.type "postgres" }}
  jupyterhub.hub.db.password: {{ (required "PostgresDB password must be specified (helm --set jupyterhub.hub.db.password=<redacted> ..)!" .Values.jupyterhub.hub.db.password) | b64enc | quote }}
{{ end }}
---
{{ if .Values.jupyterhub.ingress.enabled }}
{{ range .Values.jupyterhub.ingress.tls }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Release.Namespace }}
data:
  tls.crt: {{ (required "helm --set swan.secrets.ingress.cert=$(base64 -w0 <path>)" $.Values.swan.secrets.ingress.cert) }}
  tls.key: {{ (required "helm --set swan.secrets.ingress.key=$(base64 -w0 <path>)" $.Values.swan.secrets.ingress.key) }}
{{ end }}
{{ end }}
---
{{ if .Values.jupyterhub.proxy.https.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.jupyterhub.proxy.https.secret.name }}
  namespace: {{ $.Release.Namespace }}
data:
  tls.crt: {{ (required "helm --set swan.secrets.proxy.https.cert=$(base64 -w0 <path>)" $.Values.swan.secrets.proxy.https.cert) }}
  tls.key: {{ (required "helm --set swan.secrets.proxy.https.key=$(base64 -w0 <path>)" $.Values.swan.secrets.proxy.https.key) }}
{{ end }}