{{ if or .Values.cvmfs.deployCsiDriver .Values.cvmfs.useCsiDriver }}
{{- range .Values.cvmfs.repositories }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cvmfs-{{(split "." .mount)._0 }}
provisioner: cvmfs.csi.cern.ch
parameters:
  repository: {{ .mount }}
  {{- if .proxy }}
  proxy: {{ .proxy }}
  {{- end}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-{{.mount | replace "." "-"}}-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-{{(split "." .mount)._0 }}
---
{{- end }}
{{- end }}
