apiVersion: v2
#
name: swan-cern
type: application
# version set by bump2version search/replace
version: 0.1.21 # __swan-cern_version__
appVersion: 0.0.3
#
description: The chart to deploy SWAN at CERN
#
dependencies:
  - name: swan
    version: 0.1.20
    repository: https://registry.cern.ch/chartrepo/swan
  - name: fluentd
    repository: http://registry.cern.ch/chartrepo/cern
    version: 0.1.5
