apiVersion: v2
#
name: swan-cern
type: application
# version set by bump2version search/replace
version: 3.4.11 # __swan-cern_version__
appVersion: 0.0.3
#
description: The chart to deploy SWAN at CERN
#
dependencies:
  - name: swan
    version: 2.3.7
    repository: oci://registry.cern.ch/swan/charts
  - name: fluentd
    version: 0.4.3
    repository: https://fluent.github.io/helm-charts
  - name: gpu-operator
    version: v22.9.1
    repository: oci://registry.cern.ch/kubernetes/charts
    condition: gpu-operator.enabled
