apiVersion: v2
#
name: swan-cern
type: application
version: 0.1.7
appVersion: 0.0.3
#
description: The chart to deploy SWAN at CERN
#
dependencies:
  - name: swan
    version: 0.1.6
    repository: file://../swan
  - name: fluentd
    repository: http://registry.cern.ch/chartrepo/cern
    version: 0.1.5
