apiVersion: v2
#
name: swan-cern
type: application
# version set by bump2version search/replace
version: 2.0.3 # __swan-cern_version__
appVersion: 0.0.3
#
description: The chart to deploy SWAN at CERN
#
dependencies:
  - name: swan
    version: 1.1.0
    repository: oci://registry.cern.ch/swan/charts
  - name: fluentd
    version: 0.4.3
    repository: https://fluent.github.io/helm-charts
  - name: gpu-operator
    version: 22.9.1
    repository: https://helm.ngc.nvidia.com/nvidia
