apiVersion: v2
#
name: swan-cern
type: application
# version set by bump2version search/replace
version: 1.0.5 # __swan-cern_version__
appVersion: 0.0.3
#
description: The chart to deploy SWAN at CERN
#
dependencies:
  - name: swan
    version: 0.6.5
    repository: oci://registry.cern.ch/swan/charts
  - name: fluentd
    repository: http://registry.cern.ch/chartrepo/cern
    version: 0.1.5
  - name: gpu-operator
    version: 22.9.1
    repository: https://helm.ngc.nvidia.com/nvidia
