# Workflow to test `helm lint` and `helm package` on local version of charts
# The workflow changes the dependency between the charts to use the local version 
# on the repo to allow linting untagged changes to both parent and child charts.

name: Check Charts

on:
  # Allow calling this workflow from other workflows
  workflow_call:
  # Allow triggering this workflow manually from the github UI
  workflow_dispatch:
  # Triggers check on pull requests
  pull_request:
    branches:
      - master
      - qa

jobs:
  check_charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Temporarily change swan-cern to use local file://../swan
        uses: mikefarah/yq@1f0881fb5faf371694bfa108753cda0b824f5037 # v4.28.2
        with:
          cmd: yq -i '(.dependencies[] | select(.name == "swan")).repository = "file://../swan"' swan-cern/Chart.yaml

      - run: helm dependency update swan && helm lint swan && helm package swan

      - run: helm dependency update swan-cern && helm lint swan-cern && helm package swan-cern
