# Workflow to test `helm lint` and `helm package` on local version of charts
# The workflow changes the dependency between the charts to use the local version
# on the repo to allow linting untagged changes to both parent and child charts.

name: Check charts

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  check_charts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Temporarily change swan-cern to use local file://../swan
        run: |
          yq -i '(.dependencies[] | select(.name == "swan")).repository = "file://../swan"' swan-cern/Chart.yaml

      - name: Lint and package swan
        run: helm dependency update swan && helm lint swan && helm package swan

      - name: Lint and package swan-cern
        run: helm dependency update swan-cern && helm lint swan-cern && helm package swan-cern

      - name: Lint and package swan-cern-system
        run: helm dependency update swan-cern-system && helm lint swan-cern-system && helm package swan-cern-system
