# Reusable workflow to tag a single chart and push it to a helm registry
name: Tag Chart
run-name: Tag ${{ inputs.bump }} version of ${{ inputs.chart }} by @${{ github.actor }}

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      chart:
        description: Name of chart to tag
        required: true
        type: string
      bump:
        description: "Bump version"
        required: true
        default: patch
        type: string

    secrets:
      WORKFLOW_ACCESS_TOKEN:
        description: "A GitHub PAT token with permissions to push to master branch"
        required: true
      HELM_REPO_USERNAME:
        description: "Robot account user for the helm registry"
        required: true
      HELM_REPO_PASSWORD:
        description: "Password for the helm registry"
        required: true

    outputs:
      new_version:
        value: ${{ jobs.publish_chart.outputs.new_version }}

jobs:
  publish_chart:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      new_tag: ${{ steps.version.outputs.new_tag }}
      last_tag: ${{ steps.version.outputs.last_tag }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false # To use a different token with admin privileges instead of GITHUB_TOKEN in later steps
          ref: ${{ github.ref_name }} # Checkout latest commit on branch including new commits created in earlier steps

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.14
          enable-cache: false # Silence a warning about missing requirements.txt/pyproject.toml files in the repository

      - name: Fetch chart dependencies
        run: helm dependency update ${{ inputs.chart }}

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Calculate next version
        id: version
        run: |
          cd ${{ inputs.chart }}
          NEW_VERSION="$(uvx bump2version --dry-run ${{ inputs.bump }} --list | grep new_version= | sed -r s,"^.*=",,)"
          LAST_VERSION="$(uvx bump2version --dry-run ${{ inputs.bump }} --list | grep current_version= | sed -r s,"^.*=",,)"
          echo "new_version=${NEW_VERSION}" >> "$GITHUB_OUTPUT"
          echo "new_tag=${{ inputs.chart }}@${NEW_VERSION}" >> "$GITHUB_OUTPUT"
          echo "last_tag=${{ inputs.chart }}@${LAST_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Bump version and create local commit with tag
        run: |
          cd ${{ inputs.chart }}
          uvx bump2version ${{ inputs.bump }} --verbose --message '${{ inputs.chart }} {new_version} by @${{ github.actor }}'

      - name: Push commit + tag to origin
        env:
          WORKFLOW_ACCESS_TOKEN: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
        run: |
          git remote set-url origin "https://x-access-token:${WORKFLOW_ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push origin "${{ github.ref_name }}" --tags --atomic

      - name: Push to helm registry
        run: |
          helm registry login -u ${{ secrets.HELM_REPO_USERNAME }} -p ${{ secrets.HELM_REPO_PASSWORD }} ${{ vars.HELM_HARBOR_URL }}
          helm package ${{ inputs.chart }}
          helm push ${{ inputs.chart }}-${{ steps.version.outputs.new_version }}.tgz ${{ vars.HELM_REPO_BASE_URL }}

  publish_github_release:
    needs: [publish_chart]
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a 'GitHub Release' on the repository using $GITHUB_TOKEN
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NEW_TAG: ${{ needs.publish_chart.outputs.new_tag }}
      LAST_TAG: ${{ needs.publish_chart.outputs.last_tag }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all tags and history to check for changes
          ref: ${{ github.ref_name }}
      - name: Create GitHub Release
        run: |
          NOTES=$(git log "${LAST_TAG}..${NEW_TAG}" --pretty='- %h %s' -- ${{ inputs.chart }})
          gh release create "$NEW_TAG" --notes "$NOTES"
