# Reusable workflow to tag a single chart and push it to a helm registry
name: Tag Chart
run-name: Tag ${{ inputs.bump }} version of ${{ inputs.chart }} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      chart:
        description: Name of chart to tag
        required: true
        type: string
      bump:
        description: "Bump version"
        required: true
        default: patch
        type: string

    secrets:
      WORKFLOW_ACCESS_TOKEN:
        description: "A GitHub PAT token with permissions to push to master branch"
        required: true
      HELM_REPO_USERNAME:
        description: "Robot account user for the helm registry"
        required: true
      HELM_REPO_PASSWORD:
        description: "Password for the helm registry"
        required: true

    outputs:
      new_version:
        value: ${{ jobs.publish_chart.outputs.new_version }}

permissions: {}  # Deny all permissions by default at workflow level

jobs:
  publish_chart:
    runs-on: ubuntu-latest
    env:
      CHART: ${{ inputs.chart }}
      BUMP: ${{ inputs.bump }}
      REF_NAME: ${{ github.ref_name }} # Checkout latest commit on branch including new commits created in earlier steps
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      new_tag: ${{ steps.version.outputs.new_tag }}
      last_tag: ${{ steps.version.outputs.last_tag }}
    permissions:
      contents: write # Required to push commits and tags to master branch
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false # To use a different token with admin privileges instead of GITHUB_TOKEN in later steps

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: 3.14
          enable-cache: false # Silence a warning about missing requirements.txt/pyproject.toml files in the repository

      - name: Fetch chart dependencies
        run: helm dependency update ${CHART}

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Calculate next version
        id: version
        run: |
          cd ${CHART}
          NEW_VERSION="$(uvx bump2version --dry-run ${BUMP} --list | grep new_version= | sed -r s,"^.*=",,)"
          LAST_VERSION="$(uvx bump2version --dry-run ${BUMP} --list | grep current_version= | sed -r s,"^.*=",,)"
          echo "new_version=${NEW_VERSION}" >> "$GITHUB_OUTPUT"
          echo "new_tag=${CHART}@${NEW_VERSION}" >> "$GITHUB_OUTPUT"
          echo "last_tag=${CHART}@${LAST_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Bump version and create local commit with tag
        env:
          ACTOR: ${{ github.actor }}
        run: |
          cd ${CHART}
          uvx bump2version ${BUMP} --verbose --message "${CHART} {new_version} by @${ACTOR}"

      - name: Push commit + tag to origin
        env:
          WORKFLOW_ACCESS_TOKEN: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
        run: |
          git remote set-url origin "https://x-access-token:${WORKFLOW_ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git pull --rebase origin "${REF_NAME}"
          git push origin "${REF_NAME}" --tags --atomic

      - name: Push to helm registry
        env:
          HELM_USER: ${{ secrets.HELM_REPO_USERNAME }}
          HELM_PASS: ${{ secrets.HELM_REPO_PASSWORD }}
        run: |
          helm registry login -u ${HELM_USER} -p ${HELM_PASS} ${{ vars.HELM_HARBOR_URL }}
          helm package ${CHART}
          helm push ${CHART}-${{ steps.version.outputs.new_version }}.tgz ${{ vars.HELM_REPO_BASE_URL }}

  publish_github_release:
    needs: [publish_chart]
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a 'GitHub Release' on the repository using $GITHUB_TOKEN
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NEW_TAG: ${{ needs.publish_chart.outputs.new_tag }}
      LAST_TAG: ${{ needs.publish_chart.outputs.last_tag }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        env:
          REF_NAME: ${{ github.ref_name }}
        with:
          fetch-depth: 0 # Fetch all tags and history to check for changes
          persist-credentials: false
      - name: Create GitHub Release
        run: |
          NOTES=$(git log "${LAST_TAG}..${NEW_TAG}" --pretty='- %h %s' -- ${CHART})
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          gh release create "$NEW_TAG" --notes "$NOTES"
