name: Update jupyter and jupyterhub images

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image Name'
        required: true
      version:
        description: 'Image Version'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        ref: master

    - name: Update images version
      run: |
        IMAGE_NAME="${{ inputs.image }}"
        IMAGE_VERSION="${{ inputs.version }}"
        echo "Updating information for image = $IMAGE_NAME version = $IMAGE_VERSION"
        sed -i -E "/^[[:space:]]*name:[[:space:]]*\"?gitlab-registry\.cern\.ch\/swan\/docker-images\/${IMAGE_NAME//\//\\/}\"?[[:space:]]*$/ { n; s/^([[:space:]]*)tag:[[:space:]]*\"?[^\"]*\"?/\1tag: ${IMAGE_VERSION}/ }" swan/values.yaml swan-cern/values.yaml

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH="${{ inputs.image }}-${{ inputs.version }}"
        MESSAGE="Updated image ${{ inputs.image }} to version ${{ inputs.version }}"

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b "$BRANCH"
        git add swan/values.yaml swan-cern/values.yaml
        git commit -m "$MESSAGE"
        git push origin "$BRANCH"
        gh pr create --title "$MESSAGE" --body "" --head "$BRANCH" --base master
