name: Update jupyter and jupyterhub images

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image Name'
        required: true
      version:
        description: 'Image Version'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}  # Deny all permissions by default at workflow level

jobs:
  update-images:
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ inputs.image }}
      VERSION: ${{ inputs.version }}
    permissions:
      contents: write # Required to push commits to master branch
      pull-requests: write # Required to create pull requests

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: master
        persist-credentials: false

    - name: Update images version
      run: |
        IMAGE_NAME="${IMAGE}"
        IMAGE_VERSION="${VERSION}"
        echo "Updating information for image = $IMAGE_NAME version = $IMAGE_VERSION"
        sed -i -E "/^[[:space:]]*name:[[:space:]]*\"?gitlab-registry\.cern\.ch\/swan\/docker-images\/${IMAGE_NAME//\//\\/}\"?[[:space:]]*$/ { n; s/^([[:space:]]*)tag:[[:space:]]*\"?[^\"]*\"?/\1tag: ${IMAGE_VERSION}/ }" swan/values.yaml swan-cern/values.yaml

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH="${IMAGE}-${VERSION}"
        MESSAGE="Updated image ${IMAGE} to version ${VERSION}"

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b "$BRANCH"
        git add swan/values.yaml swan-cern/values.yaml
        git commit -m "$MESSAGE"
        git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push origin "$BRANCH"
        gh pr create --title "$MESSAGE" --body "" --head "$BRANCH" --base master
